# Generated by Django 4.2.25 on 2025-10-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('edad', models.CharField(choices=[('18-24', '18-24'), ('25-30', '25-30')], max_length=10)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('No Binario', 'No Binario'), ('Prefiero no decir', 'Prefiero no decir')], max_length=20)),
                ('ciudad', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('situacion_educativa', models.CharField(max_length=100)),
                ('estrato_socioeconomico', models.CharField(choices=[('Bajo', 'Bajo'), ('Medio-Bajo', 'Medio-Bajo'), ('Medio', 'Medio'), ('Medio-Alto', 'Medio-Alto')], max_length=20)),
                ('estatus_laboral', models.CharField(choices=[('Empleado Publica', 'Empleado Institución Pública'), ('Empleado Privada', 'Empleado Empresa Privada'), ('Desempleado', 'Desempleado'), ('Emprendedor', 'Emprendedor'), ('Freelance', 'Freelance'), ('Innovador', 'Innovador')], max_length=50)),
                ('contribuye_familia', models.CharField(choices=[('Si, completamente', 'Sí, completamente'), ('Si, parcialmente', 'Sí, parcialmente'), ('No', 'No, aún no')], max_length=20)),
                ('nivel_ingreso', models.CharField(choices=[('Sin ingresos', 'Sin ingresos'), ('Bajos', 'Ingresos bajos'), ('Medios', 'Ingresos medios'), ('Altos', 'Ingresos altos')], max_length=20)),
                ('intencion_voto', models.CharField(choices=[('Rodrigo Paz Pereira', 'Rodrigo Paz Pereira'), ('Jorge Quiroga Ramírez', 'Jorge Quiroga Ramírez'), ('Blanco', 'Voto Blanco'), ('Nulo', 'Voto Nulo'), ('Indeciso', 'Aún no lo decido')], max_length=50)),
                ('firmeza_voto', models.IntegerField()),
                ('alineamiento_ideologico', models.CharField(choices=[('Izquierda/Progresista', 'Izquierda/Progresista'), ('Centro-Izquierda', 'Centro-Izquierda'), ('Centro', 'Centro'), ('Centro-Derecha', 'Centro-Derecha'), ('Derecha Conservadora', 'Derecha Conservadora')], max_length=30)),
                ('influencia_entorno', models.IntegerField()),
                ('motivacion_voto', models.CharField(max_length=100)),
                ('estabilidad', models.IntegerField()),
                ('empleo', models.IntegerField()),
                ('deuda', models.IntegerField()),
                ('calidad', models.IntegerField()),
                ('becas', models.IntegerField()),
                ('corrupcion_justicia', models.IntegerField()),
                ('salud', models.IntegerField()),
                ('seguridad_ciudadana', models.IntegerField()),
                ('cambio_climatico', models.IntegerField()),
                ('temaGenero', models.IntegerField()),
                ('derechos_sociales', models.IntegerField()),
                ('modelo_desarrollo', models.IntegerField()),
                ('PropuestaCandidatoNegativo', models.IntegerField()),
                ('descontentoCandidato', models.IntegerField()),
                ('experiencia_gestion_paz', models.IntegerField()),
                ('honestidad_paz', models.IntegerField()),
                ('capacidad_unir_paz', models.IntegerField()),
                ('conexion_jovenes_paz', models.IntegerField()),
                ('liderazgo_paz', models.IntegerField()),
                ('propuestas_claras_paz', models.IntegerField()),
                ('experiencia_gestion_tuto', models.IntegerField()),
                ('honestidad_tuto', models.IntegerField()),
                ('capacidad_unir_tuto', models.IntegerField()),
                ('conexion_jovenes_tuto', models.IntegerField()),
                ('liderazgo_tuto', models.IntegerField()),
                ('propuestas_claras_tuto', models.IntegerField()),
                ('medio_influencia', models.CharField(max_length=50)),
                ('confianza_redes', models.IntegerField()),
                ('conocimiento_economico', models.CharField(max_length=50)),
                ('influencia_imagen', models.IntegerField()),
                ('cambio_opinion_debates', models.BooleanField()),
                ('optimismo_futuro', models.IntegerField()),
                ('emocion_dominante', models.CharField(max_length=50)),
                ('percepcion_eficacia', models.BooleanField()),
                ('confianza_expertos', models.IntegerField()),
                ('reaccion_escandalo', models.IntegerField()),
                ('reaccion_bonos', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
