# Generated by Django 4.2.25 on 2025-10-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
