# Generated by Django 4.2.25 on 2025-10-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_alter_encuesta_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='profesion_carrera',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='ciudad',
            field=models.CharField(choices=[('La Paz', 'La Paz'), ('Cochabamba', 'Cochabamba'), ('Santa Cruz', 'Santa Cruz'), ('Oruro', 'Oruro'), ('Potosí', 'Potosí'), ('Chuquisaca', 'Chuquisaca'), ('Tarija', 'Tarija'), ('Beni', 'Beni'), ('Pando', 'Pando')], max_length=50),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='motivacion_voto',
            field=models.CharField(choices=[('Las propuestas del candidato', 'Las propuestas del candidato'), ('Su experiencia o trayectoria', 'Su experiencia o trayectoria'), ('Su ideología o valores', 'Su ideología o valores'), ('El rechazo al otro candidato', 'El rechazo al otro candidato'), ('Opiniones de su entorno', 'Opiniones de su entorno'), ('Ninguna', 'Ninguna')], max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='situacion_educativa',
            field=models.CharField(choices=[('Estudiante Universitario', 'Estudiante Universitario'), ('Recien Profecionalizado', 'Recien Profecionalizado')], max_length=100),
        ),
    ]
